"""
src/data_loader.py
==================
Custom PyTorch Dataset that loads MRI images alongside synthetic tabular
clinical data for multimodal Alzheimer classification.

Expected directory layout (after running data/download_data.sh):

    data/raw/Alzheimer_s Dataset/
        train/
            NonDemented/        *.jpg
            VeryMildDemented/   *.jpg
            MildDemented/       *.jpg
            ModerateDemented/   *.jpg
        test/
            ...

Tabular data is loaded from data/synthetic_tabular.csv (generated by
data/generate_synthetic.py). Images are matched to tabular rows by their
positional index within each class, cycling over the tabular rows if there
are more images than synthetic patients.

Usage:
    from src.data_loader import build_dataloaders
    train_loader, val_loader, test_loader, meta = build_dataloaders()
"""

import os
import random
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms

# ── Class definitions ──────────────────────────────────────────────────────────

CLASS_NAMES = ["NonDemented", "VeryMildDemented", "MildDemented", "ModerateDemented"]
CLASS_TO_IDX = {c: i for i, c in enumerate(CLASS_NAMES)}

# ── Default paths (relative to project root) ──────────────────────────────────

DATA_ROOT = Path(__file__).resolve().parent.parent / "data"
TABULAR_CSV = DATA_ROOT / "synthetic_tabular.csv"

def get_raw_root(data_root: Path) -> Path:
    """Automatically find the directory containing 'train' and 'test' folders."""
    raw_path = data_root / "raw"
    # Look for any subdirectory that contains a 'train' folder
    for p in raw_path.rglob("train"):
        if p.is_dir():
            return p.parent
    return raw_path  # Fallback

# ── ImageNet normalisation (works for grayscale→3ch MRI too) ──────────────────

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]


def get_transforms(split: str) -> transforms.Compose:
    """Return torchvision transform pipeline for train / val / test splits."""
    if split == "train":
        return transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.Grayscale(num_output_channels=3),   # MRI → 3-ch
            transforms.RandomHorizontalFlip(p=0.5),
            transforms.RandomRotation(degrees=10),
            transforms.ColorJitter(brightness=0.1, contrast=0.1),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])
    else:  # val / test — no augmentation
        return transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.Grayscale(num_output_channels=3),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ])


def _collect_image_paths(root: Path, split: str) -> List[Tuple[Path, int]]:
    """Recursively collect (image_path, class_idx) from a Kaggle-style split folder."""
    split_dir = root / split
    if not split_dir.exists():
        raise FileNotFoundError(
            f"Split directory not found: {split_dir}\n"
            f"Run: bash data/download_data.sh"
        )
    samples = []
    for class_name in CLASS_NAMES:
        class_dir = split_dir / class_name
        if not class_dir.exists():
            continue
        for ext in ("*.jpg", "*.jpeg", "*.png"):
            for img_path in sorted(class_dir.glob(ext)):
                samples.append((img_path, CLASS_TO_IDX[class_name]))
    return samples


class AlzheimerDataset(Dataset):
    """
    Multimodal dataset returning (image_tensor, tabular_tensor, label).

    Args:
        samples:    list of (image_path, class_idx) tuples
        tabular_df: DataFrame with pre-scaled tabular features (one row per patient)
        transform:  torchvision transform to apply to each image
        class_counts: dict mapping class_idx → number of images in that class
                      (used to cycle tabular rows within each class)
    """

    def __init__(
        self,
        samples: List[Tuple[Path, int]],
        tabular_df: pd.DataFrame,
        transform: Optional[transforms.Compose] = None,
        class_row_map: Optional[Dict[int, List[int]]] = None,
        tabular_dropout: float = 0.0,
    ):
        self.samples = samples
        self.tabular = tabular_df
        self.transform = transform
        self.class_row_map = class_row_map or {}
        self.tabular_dropout = tabular_dropout

        # Running counters so each class cycles through its tabular rows
        self._class_counters = {idx: 0 for idx in CLASS_TO_IDX.values()}

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int):
        img_path, label = self.samples[idx]

        # ── Load image ────────────────────────────────────────────────────────
        image = Image.open(img_path).convert("RGB")
        if self.transform:
            image = self.transform(image)

        # ── Fetch matching tabular row (cycle within class) ───────────────────
        rows = self.class_row_map.get(label, list(range(len(self.tabular))))
        row_idx = rows[idx % len(rows)]
        tab_row = self.tabular.iloc[row_idx]
        
        # Apply Tabular Dropout: Randomly zero out metadata to force Vision dependency
        if self.tabular_dropout > 0 and random.random() < self.tabular_dropout:
            tabular = torch.zeros(len(tab_row), dtype=torch.float32)
        else:
            tabular = torch.tensor(tab_row.values.astype(np.float32), dtype=torch.float32)

        return image, tabular, torch.tensor(label, dtype=torch.long)


def _prepare_tabular(csv_path: Path = TABULAR_CSV):
    """Load and scale tabular CSV. Returns (scaled_df, scaler, feature_dim, class_row_map)."""
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Tabular CSV not found: {csv_path}\n"
            f"Run: python data/generate_synthetic.py"
        )

    df = pd.read_csv(csv_path)

    # Numeric features only (drop id and label columns)
    feature_cols = ["age", "mmse", "cdr", "education_years", "apoe4"]
    X = df[feature_cols].copy()

    scaler = StandardScaler()
    X_scaled = pd.DataFrame(scaler.fit_transform(X), columns=feature_cols)

    # Build a map: class_idx → list of row indices in the tabular CSV
    class_row_map = {}
    for class_name, class_idx in CLASS_TO_IDX.items():
        mask = df["class_label"] == class_name
        class_row_map[class_idx] = list(df[mask].index)

    return X_scaled, scaler, len(feature_cols), class_row_map


def build_dataloaders(
    data_root: Path = DATA_ROOT,
    tabular_csv: Path = TABULAR_CSV,
    val_size: float = 0.1,
    batch_size: int = 16,
    num_workers: int = 4,
    seed: int = 42,
    tabular_dropout: float = 0.2,
) -> Tuple[DataLoader, DataLoader, DataLoader, dict]:
    """
    Build train / val / test DataLoaders.

    Returns:
        train_loader, val_loader, test_loader, metadata_dict
        metadata_dict contains: class_names, class_weights, tabular_dim, scaler
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    # ── Find raw root automatically ──────────────────────────────────────────
    raw_root = get_raw_root(data_root)

    # ── Collect all image paths per split ─────────────────────────────────────
    train_val_samples = _collect_image_paths(raw_root, "train")
    test_samples      = _collect_image_paths(raw_root, "test")

    # ── Stratified train/val split ────────────────────────────────────────────
    labels = [s[1] for s in train_val_samples]
    train_samples, val_samples = train_test_split(
        train_val_samples, test_size=val_size, stratify=labels, random_state=seed
    )

    # ── Tabular data ──────────────────────────────────────────────────────────
    tabular_df, scaler, tabular_dim, class_row_map = _prepare_tabular(tabular_csv)

    # ── Compute class weights for imbalanced data ─────────────────────────────
    train_labels = [s[1] for s in train_samples]
    class_counts = np.bincount(train_labels, minlength=len(CLASS_NAMES))
    
    # Use square root of counts to dampen extreme weights for minority classes
    class_weights = torch.tensor(
        1.0 / np.sqrt(class_counts + 1e-6), dtype=torch.float32
    )
    class_weights /= class_weights.sum()

    # ── Build Dataset objects ─────────────────────────────────────────────────
    ds_train = AlzheimerDataset(train_samples, tabular_df, get_transforms("train"), class_row_map, tabular_dropout=tabular_dropout)
    ds_val   = AlzheimerDataset(val_samples,   tabular_df, get_transforms("val"),   class_row_map, tabular_dropout=0.0)
    ds_test  = AlzheimerDataset(test_samples,  tabular_df, get_transforms("test"),  class_row_map, tabular_dropout=0.0)

    loader_kwargs = dict(batch_size=batch_size, num_workers=num_workers, pin_memory=True)

    train_loader = DataLoader(ds_train, shuffle=True,  **loader_kwargs)
    val_loader   = DataLoader(ds_val,   shuffle=False, **loader_kwargs)
    test_loader  = DataLoader(ds_test,  shuffle=False, **loader_kwargs)

    meta = {
        "class_names":    CLASS_NAMES,
        "class_weights":  class_weights,
        "tabular_dim":    tabular_dim,
        "scaler":         scaler,
        "n_train":        len(ds_train),
        "n_val":          len(ds_val),
        "n_test":         len(ds_test),
    }

    print(f"✅  DataLoaders ready — train: {meta['n_train']} | val: {meta['n_val']} | test: {meta['n_test']}")
    print(f"    Tabular feature dim: {tabular_dim}")
    print(f"    Class weights: {class_weights.numpy().round(4)}")

    return train_loader, val_loader, test_loader, meta
